// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7wPTpCiVFS89hx7M8x2eQCG3ZMwpAXM',
    appId: '1:886675431042:web:dcd9d96515c874ddcf1e9b',
    messagingSenderId: '886675431042',
    projectId: 'na9raw-750c6',
    authDomain: 'na9raw-750c6.firebaseapp.com',
    storageBucket: 'na9raw-750c6.firebasestorage.app',
    measurementId: 'G-JMSH25K7WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANTmyhgqk4NlzFJ-UnRS2O-T2Y3DAbPHo',
    appId: '1:886675431042:android:2ed0cd7214ead4d4cf1e9b',
    messagingSenderId: '886675431042',
    projectId: 'na9raw-750c6',
    storageBucket: 'na9raw-750c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNNB_uoZPGXnnsUeuILQl-_fpO1irDDpY',
    appId: '1:886675431042:ios:b2067d569505a6bacf1e9b',
    messagingSenderId: '886675431042',
    projectId: 'na9raw-750c6',
    storageBucket: 'na9raw-750c6.firebasestorage.app',
    iosClientId: '886675431042-h2lis0tuv3rn6s7tf7bpc58ekgtq26md.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNNB_uoZPGXnnsUeuILQl-_fpO1irDDpY',
    appId: '1:886675431042:ios:b2067d569505a6bacf1e9b',
    messagingSenderId: '886675431042',
    projectId: 'na9raw-750c6',
    storageBucket: 'na9raw-750c6.firebasestorage.app',
    iosClientId: '886675431042-h2lis0tuv3rn6s7tf7bpc58ekgtq26md.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP7wPTpCiVFS89hx7M8x2eQCG3ZMwpAXM',
    appId: '1:886675431042:web:552e7f434b50cb55cf1e9b',
    messagingSenderId: '886675431042',
    projectId: 'na9raw-750c6',
    authDomain: 'na9raw-750c6.firebaseapp.com',
    storageBucket: 'na9raw-750c6.firebasestorage.app',
    measurementId: 'G-L4R748D4HW',
  );

}